sudo: required
language: generic
services:
  - docker
  
before_install:
  - docker build -t deltics/s8-fib-app-test -f ./app/dockerfile.dev ./app

script:
  - docker run -e CI=true deltics/s8-fib-app-test npm test

after_success:
  - docker build -t deltics/s8-fib-api ./api
  - docker build -t deltics/s8-fib-app ./app
  - docker build -t deltics/s8-fib-nginx ./nginx
  - docker build -t deltics/s8-fib-worker ./worker
  # login to docker
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_UID" --password-stdin
  # push images to docker hub
  - docker push deltics/s8-fib-api
  - docker push deltics/s8-fib-app
  - docker push deltics/s8-fib-nginx
  - docker push deltics/s8-fib-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: s8-fib
  env: s8fib-env
  bucket_name: elasticbeanstalk-us-west-2-534848308234
  bucket_path: s8-fib
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY