sudo: required
language: generic
services:
  - docker
  
before_install:
  - docker build -t deltics/s8-fib-app-test -f ./app/dockerfile.dev ./app

script:
  - docker run -e CI=true deltics/s8-fib-app-test npm test

after_success:
  - docker build -t deltics/s8-fib-api ./api
  - docker build -t deltics/s8-fib-app ./app
  - docker build -t deltics/s8-fib-nginx ./nginx
  - docker build -t deltics/s8-fib-worker ./worker
  # login to docker
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_UID" --password-stdin
  # push images to docker hub
  - docker push deltics/s8-fib-api
  - docker push deltics/s8-fib-app
  - docker push deltics/s8-fib-nginx
  - docker push deltics/s8-fib-worker
