version: '3'
services:
  nginx:
    image: deltics/s8-fib-nginx
    mem_limit: 128m
    hostname: app
    ports:
      - 80:80
  app:
    image: deltics/s8-fib-app
    mem_limit: 128m
    hostname: app
  api:
    image: deltics/s8-fib-api
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGHOST=$PGHOST
      - PGPORT=$PGPORT
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
  worker:
    image: deltics/s8-fib-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
