FROM node:16-alpine as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
COPY nginx/config.prod /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
